
sudo: false

language: generic

dist: trusty

env:
  global:
    - LUAROCKS_VERSION=3.0.0

addons:
  apt:
    sources:
      # Use the official APT repositories from OpenResty (which includes LuaJIT 2.1.0-beta3),
      # because LuaJIT on trusty is quite old.
      - sourceline: 'deb http://openresty.org/package/ubuntu trusty main'
        key_url: 'https://openresty.org/package/pubkey.gpg'
    packages:
      - libvips-dev

before_install:
  - bash .ci/install-vips.sh
  - bash .ci/install-luarocks.sh
    --with-lua=/usr/local/openresty/luajit/
    --lua-suffix=jit-2.1.0-beta3
    --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1
  - eval `luarocks path`

script:
