name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up LuaJIT
      run: |
        sudo apt-get -yqq install wget unzip luajit libluajit-5.1-dev
    - name: Set up Luarocks
      run: |
        wget https://luarocks.org/releases/luarocks-3.3.1.tar.gz
        tar zxpf luarocks-3.3.1.tar.gz
        cd luarocks-3.3.1
        ./configure --with-lua-include=/usr/include/luajit-2.1 --with-lua-lib=/usr/lib/x86_64-linux-gnu
        make
        sudo make install
    - name: Install rocks
      run: |
        sudo luarocks install luasocket
        sudo luarocks install luautf8
        sudo luarocks install luafilesystem
    - name: Run REPL test
      run: |
        ./OpenNefia_REPL test
